#!/usr/bin/env bash

PLINK=plink1.9
SMR=smr

main() {
    GENETIC=~/Data/CTMM/genome2/rsync/ctmm_1kGp3GoNL5_RAW_chr2 
    EQTL_FILE=$(readlink -f ../qtlnom.txt)
    BESD_OUTPUT=$(readlink -f q/mybesd)

    BUILD_DIR="${TMPDIR:-/tmp}/build_$RANDOM"
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR

    awk '{print $8}' $EQTL_FILE > extract_snps.txt
    $PLINK --bfile $GENETIC --extract extract_snps.txt --make-just-bim
    $SMR --eqtl-summary $EQTL_FILE --qtltools-nominal-format --make-besd --out $BESD_OUTPUT
    $SMR --beqtl-summary $BESD_OUTPUT --update-esi plink.bim

    cd ..
    rm -r $BESD_OUTPUT.bak.esi $BUILD_DIR
}

mkdir -p q
set -ex
main

