#!/usr/bin/env bash

set -ex

source $1

SMR=$CONFIG_SMR
GWAS=$CONFIG_GWAS

LINE=$(cat "${CONFIG_JOBDIR}/make-besd.param" | sed "${SGE_TASK_ID}p;d")
echo ===
VARIANT=$(echo "$LINE" | awk '$0=$1')
GENETIC=$(echo "$LINE" | awk '$0=$2')
BESD=$(echo "$LINE" | awk '$0=$4')
BESD=$(readlink -f $BESD)
echo TaskID: $SGE_TASK_ID / "$VARIANT" '/' $BESD
echo ===

main() {
    extra_ops_gw=""
    if $GW; then
        extra_ops_gw="--thread-num 12"
    fi
    $SMR \
        --bfile $GENETIC \
        --gwas-summary $GWAS \
        --beqtl-summary $BESD \
        --out ${CONFIG_JOBDIR}/smr/${VARIANT}.out $extra_ops_gw \
             | tee ${CONFIG_JOBDIR}/smr/${VARIANT}.stdout
}

main
